#!/bin/bash
#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# File name: diy-part2.sh
# Description: OpenWrt DIY script part 2 (After Update feeds)
#

KERNEL_CONFIG="target/linux/ipq50xx/config-5.4"

if [ -f "$KERNEL_CONFIG" ]; then
	sed -i '/CONFIG_WIREGUARD/d;/CONFIG_NET_UDP_TUNNEL/d;/CONFIG_CRYPTO_LIB_CHACHA/d;/CONFIG_CRYPTO_LIB_CHACHA_GENERIC/d;/CONFIG_CRYPTO_ARCH_HAVE_LIB_CHACHA/d;/CONFIG_CRYPTO_LIB_CHACHA20POLY1305/d;/CONFIG_CRYPTO_LIB_POLY1305/d;/CONFIG_CRYPTO_LIB_POLY1305_GENERIC/d;/CONFIG_CRYPTO_LIB_POLY1305_RSIZE/d;/CONFIG_CRYPTO_ARCH_HAVE_LIB_POLY1305/d;/CONFIG_CRYPTO_LIB_BLAKE2S/d;/CONFIG_CRYPTO_LIB_BLAKE2S_GENERIC/d;/CONFIG_CRYPTO_ARCH_HAVE_LIB_BLAKE2S/d;/CONFIG_CRYPTO_LIB_CURVE25519/d;/CONFIG_CRYPTO_LIB_CURVE25519_GENERIC/d;/CONFIG_CRYPTO_ARCH_HAVE_LIB_CURVE25519/d' "$KERNEL_CONFIG"

	cat >> "$KERNEL_CONFIG" <<'EOF'
CONFIG_WIREGUARD=m
# CONFIG_WIREGUARD_DEBUG is not set
CONFIG_NET_UDP_TUNNEL=m
CONFIG_CRYPTO_LIB_CHACHA=m
CONFIG_CRYPTO_LIB_CHACHA_GENERIC=m
# CONFIG_CRYPTO_ARCH_HAVE_LIB_CHACHA is not set
CONFIG_CRYPTO_LIB_CHACHA20POLY1305=m
CONFIG_CRYPTO_LIB_POLY1305=m
CONFIG_CRYPTO_LIB_POLY1305_GENERIC=m
CONFIG_CRYPTO_LIB_POLY1305_RSIZE=9
# CONFIG_CRYPTO_ARCH_HAVE_LIB_POLY1305 is not set
CONFIG_CRYPTO_LIB_BLAKE2S=m
CONFIG_CRYPTO_LIB_BLAKE2S_GENERIC=m
# CONFIG_CRYPTO_ARCH_HAVE_LIB_BLAKE2S is not set
CONFIG_CRYPTO_LIB_CURVE25519=m
CONFIG_CRYPTO_LIB_CURVE25519_GENERIC=m
# CONFIG_CRYPTO_ARCH_HAVE_LIB_CURVE25519 is not set
EOF
fi
